SELECT SCHEMA_NAME as "name" FROM SYS.SCHEMAS WHERE HAS_PRIVILEGES = 'TRUE';

SELECT TABLE_NAME as "name" FROM M_TABLES WHERE SCHEMA_NAME = 'TIMP' ORDER BY TABLE_NAME;

SELECT COLUMN_NAME, POSITION, LENGTH, SCALE, IS_NULLABLE, CS_DATA_TYPE_NAME, TABLE_NAME FROM TABLE_COLUMNS WHERE SCHEMA_NAME = ${schemaName} AND TABLE_NAME = ${tableName} ORDER BY POSITION